name 'abcd-app'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures abcd-app'
long_description 'Installs/Configures abcd-app'
version '0.1.0'
