---
driver:
  name: vagrant

  network:
    - ["forwarded_port", {guest: 3306, host: 3306}]
    - ["private_network", {ip: "10.0.3.16"}]

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[abc-db::default]
    attributes:
