---
driver:
  name: vagrant

  network:
    - ["forwarded_port", {guest: 8080, host: 8080}]
    - ["private_network", {ip: "10.0.3.15"}]

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[abc-app::default]
    attributes:
