name 'abc-app'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures abc-development'
long_description 'Installs/Configures abc-development'
version '0.1.0'

depends 'apt'
depends 'tarball'